<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuestionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('questions')->insert([
            // Subject ID 1: Introduction to Medicine and Emergency
            [
                'text' => 'What is the primary function of the heart?',
                'answers' => json_encode([
                    ['text' => 'Pump blood', 'is_correct' => true],
                    ['text' => 'Filter toxins', 'is_correct' => false],
                    ['text' => 'Produce hormones', 'is_correct' => false],
                    ['text' => 'Digest food', 'is_correct' => false],
                ]),
                'difficulty' => 'easy',
                'points' => 1,
                'subject_id' => 1,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'Which of the following is NOT a vital sign?',
                'answers' => json_encode([
                    ['text' => 'Blood pressure', 'is_correct' => false],
                    ['text' => 'Heart rate', 'is_correct' => false],
                    ['text' => 'Body temperature', 'is_correct' => false],
                    ['text' => 'Skin color', 'is_correct' => true],
                ]),
                'difficulty' => 'medium',
                'points' => 2,
                'subject_id' => 1,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'What is the first step in managing a patient in cardiac arrest?',
                'answers' => json_encode([
                    ['text' => 'Start CPR', 'is_correct' => true],
                    ['text' => 'Administer epinephrine', 'is_correct' => false],
                    ['text' => 'Check for pulse', 'is_correct' => false],
                    ['text' => 'Defibrillate', 'is_correct' => false],
                ]),
                'difficulty' => 'hard',
                'points' => 3,
                'subject_id' => 1,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'Which of the following is a symptom of myocardial infarction?',
                'answers' => json_encode([
                    ['text' => 'Chest pain', 'is_correct' => true],
                    ['text' => 'Headache', 'is_correct' => false],
                    ['text' => 'Abdominal pain', 'is_correct' => false],
                    ['text' => 'Joint pain', 'is_correct' => false],
                ]),
                'difficulty' => 'easy',
                'points' => 1,
                'subject_id' => 1,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'What is the normal range for adult respiratory rate?',
                'answers' => json_encode([
                    ['text' => '12-20 breaths per minute', 'is_correct' => true],
                    ['text' => '8-10 breaths per minute', 'is_correct' => false],
                    ['text' => '25-30 breaths per minute', 'is_correct' => false],
                    ['text' => '30-40 breaths per minute', 'is_correct' => false],
                ]),
                'difficulty' => 'medium',
                'points' => 2,
                'subject_id' => 1,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],

            // Subject ID 2: Human and Environment
            [
                'text' => 'Which of the following is a major environmental factor affecting human health?',
                'answers' => json_encode([
                    ['text' => 'Air pollution', 'is_correct' => true],
                    ['text' => 'Genetic mutations', 'is_correct' => false],
                    ['text' => 'Viral infections', 'is_correct' => false],
                    ['text' => 'Dietary habits', 'is_correct' => false],
                ]),
                'difficulty' => 'easy',
                'points' => 1,
                'subject_id' => 2,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'What is the primary cause of ozone layer depletion?',
                'answers' => json_encode([
                    ['text' => 'Chlorofluorocarbons (CFCs)', 'is_correct' => true],
                    ['text' => 'Carbon dioxide', 'is_correct' => false],
                    ['text' => 'Methane', 'is_correct' => false],
                    ['text' => 'Nitrous oxide', 'is_correct' => false],
                ]),
                'difficulty' => 'medium',
                'points' => 2,
                'subject_id' => 2,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'Which disease is directly linked to water pollution?',
                'answers' => json_encode([
                    ['text' => 'Cholera', 'is_correct' => true],
                    ['text' => 'Malaria', 'is_correct' => false],
                    ['text' => 'Tuberculosis', 'is_correct' => false],
                    ['text' => 'Influenza', 'is_correct' => false],
                ]),
                'difficulty' => 'hard',
                'points' => 3,
                'subject_id' => 2,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'What is the main health risk associated with prolonged exposure to loud noise?',
                'answers' => json_encode([
                    ['text' => 'Hearing loss', 'is_correct' => true],
                    ['text' => 'Vision impairment', 'is_correct' => false],
                    ['text' => 'Skin cancer', 'is_correct' => false],
                    ['text' => 'Respiratory issues', 'is_correct' => false],
                ]),
                'difficulty' => 'easy',
                'points' => 1,
                'subject_id' => 2,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'Which of the following is a vector-borne disease?',
                'answers' => json_encode([
                    ['text' => 'Dengue fever', 'is_correct' => true],
                    ['text' => 'Influenza', 'is_correct' => false],
                    ['text' => 'Tuberculosis', 'is_correct' => false],
                    ['text' => 'Cholera', 'is_correct' => false],
                ]),
                'difficulty' => 'medium',
                'points' => 2,
                'subject_id' => 2,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],

            // Subject ID 3: Motherhood and Childhood
            [
                'text' => 'What is the recommended duration of exclusive breastfeeding?',
                'answers' => json_encode([
                    ['text' => '6 months', 'is_correct' => true],
                    ['text' => '3 months', 'is_correct' => false],
                    ['text' => '9 months', 'is_correct' => false],
                    ['text' => '12 months', 'is_correct' => false],
                ]),
                'difficulty' => 'easy',
                'points' => 1,
                'subject_id' => 3,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'Which vitamin is essential for preventing neural tube defects in newborns?',
                'answers' => json_encode([
                    ['text' => 'Folic acid', 'is_correct' => true],
                    ['text' => 'Vitamin C', 'is_correct' => false],
                    ['text' => 'Vitamin D', 'is_correct' => false],
                    ['text' => 'Vitamin B12', 'is_correct' => false],
                ]),
                'difficulty' => 'medium',
                'points' => 2,
                'subject_id' => 3,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'What is the most common cause of postpartum hemorrhage?',
                'answers' => json_encode([
                    ['text' => 'Uterine atony', 'is_correct' => true],
                    ['text' => 'Placenta previa', 'is_correct' => false],
                    ['text' => 'Coagulopathy', 'is_correct' => false],
                    ['text' => 'Cervical laceration', 'is_correct' => false],
                ]),
                'difficulty' => 'hard',
                'points' => 3,
                'subject_id' => 3,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'Which of the following is a common symptom of preeclampsia?',
                'answers' => json_encode([
                    ['text' => 'High blood pressure', 'is_correct' => true],
                    ['text' => 'Low blood sugar', 'is_correct' => false],
                    ['text' => 'Increased urine output', 'is_correct' => false],
                    ['text' => 'Decreased heart rate', 'is_correct' => false],
                ]),
                'difficulty' => 'easy',
                'points' => 1,
                'subject_id' => 3,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'What is the primary cause of sudden infant death syndrome (SIDS)?',
                'answers' => json_encode([
                    ['text' => 'Unknown', 'is_correct' => true],
                    ['text' => 'Infections', 'is_correct' => false],
                    ['text' => 'Genetic disorders', 'is_correct' => false],
                    ['text' => 'Trauma', 'is_correct' => false],
                ]),
                'difficulty' => 'medium',
                'points' => 2,
                'subject_id' => 3,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],

            // Subject ID 4: Arabic Language (1)
            // [
            //     'text' => 'What is the Arabic word for "heart"?',
            //     'answers' => json_encode([
            //         ['text' => 'قلب', 'is_correct' => true],
            //         ['text' => 'كبد', 'is_correct' => false],
            //         ['text' => 'رئة', 'is_correct' => false],
            //         ['text' => 'دماغ', 'is_correct' => false],
            //     ]),
            //     'difficulty' => 'easy',
            //     'points' => 1,
            //     'subject_id' => 4,
            //     'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
            //     'updated_at' => now(),
            // ],
            // [
            //     'text' => 'Which of the following is the correct Arabic translation for "hospital"?',
            //     'answers' => json_encode([
            //         ['text' => 'مستشفى', 'is_correct' => true],
            //         ['text' => 'عيادة', 'is_correct' => false],
            //         ['text' => 'صيدلية', 'is_correct' => false],
            //         ['text' => 'مختبر', 'is_correct' => false],
            //     ]),
            //     'difficulty' => 'medium',
            //     'points' => 2,
            //     'subject_id' => 4,
            //     'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
            //     'updated_at' => now(),
            // ],
            // [
            //     'text' => 'What is the plural form of the Arabic word "طبيب"?',
            //     'answers' => json_encode([
            //         ['text' => 'أطباء', 'is_correct' => true],
            //         ['text' => 'طبيبات', 'is_correct' => false],
            //         ['text' => 'طبيبون', 'is_correct' => false],
            //         ['text' => 'طبيبي', 'is_correct' => false],
            //     ]),
            //     'difficulty' => 'hard',
            //     'points' => 3,
            //     'subject_id' => 4,
            //     'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
            //     'updated_at' => now(),
            // ],
            // [
            //     'text' => 'Which Arabic word means "medicine"?',
            //     'answers' => json_encode([
            //         ['text' => 'طب', 'is_correct' => true],
            //         ['text' => 'جراحة', 'is_correct' => false],
            //         ['text' => 'علاج', 'is_correct' => false],
            //         ['text' => 'دواء', 'is_correct' => false],
            //     ]),
            //     'difficulty' => 'easy',
            //     'points' => 1,
            //     'subject_id' => 4,
            //     'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
            //     'updated_at' => now(),
            // ],
            // [
            //     'text' => 'What is the Arabic term for "emergency"?',
            //     'answers' => json_encode([
            //         ['text' => 'طوارئ', 'is_correct' => true],
            //         ['text' => 'إسعاف', 'is_correct' => false],
            //         ['text' => 'حالة', 'is_correct' => false],
            //         ['text' => 'عاجل', 'is_correct' => false],
            //     ]),
            //     'difficulty' => 'medium',
            //     'points' => 2,
            //     'subject_id' => 4,
            //     'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
            //     'updated_at' => now(),
            // ],

            // Subject ID 5: Arabic Language (2)
            // [
            //     'text' => 'What is the Arabic word for "patient"?',
            //     'answers' => json_encode([
            //         ['text' => 'مريض', 'is_correct' => true],
            //         ['text' => 'طبيب', 'is_correct' => false],
            //         ['text' => 'ممرض', 'is_correct' => false],
            //         ['text' => 'جراح', 'is_correct' => false],
            //     ]),
            //     'difficulty' => 'easy',
            //     'points' => 1,
            //     'subject_id' => 5,
            //     'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
            //     'updated_at' => now(),
            // ],
            // [
            //     'text' => 'Which of the following is the correct Arabic translation for "surgery"?',
            //     'answers' => json_encode([
            //         ['text' => 'جراحة', 'is_correct' => true],
            //         ['text' => 'طب', 'is_correct' => false],
            //         ['text' => 'علاج', 'is_correct' => false],
            //         ['text' => 'دواء', 'is_correct' => false],
            //     ]),
            //     'difficulty' => 'medium',
            //     'points' => 2,
            //     'subject_id' => 5,
            //     'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
            //     'updated_at' => now(),
            // ],
            // [
            //     'text' => 'What is the plural form of the Arabic word "ممرض"?',
            //     'answers' => json_encode([
            //         ['text' => 'ممرضون', 'is_correct' => true],
            //         ['text' => 'ممرضات', 'is_correct' => false],
            //         ['text' => 'ممرضين', 'is_correct' => false],
            //         ['text' => 'ممرضي', 'is_correct' => false],
            //     ]),
            //     'difficulty' => 'hard',
            //     'points' => 3,
            //     'subject_id' => 5,
            //     'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
            //     'updated_at' => now(),
            // ],
            // [
            //     'text' => 'Which Arabic word means "pharmacy"?',
            //     'answers' => json_encode([
            //         ['text' => 'صيدلية', 'is_correct' => true],
            //         ['text' => 'مستشفى', 'is_correct' => false],
            //         ['text' => 'عيادة', 'is_correct' => false],
            //         ['text' => 'مختبر', 'is_correct' => false],
            //     ]),
            //     'difficulty' => 'easy',
            //     'points' => 1,
            //     'subject_id' => 5,
            //     'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
            //     'updated_at' => now(),
            // ],
            // [
            //     'text' => 'What is the Arabic term for "diagnosis"?',
            //     'answers' => json_encode([
            //         ['text' => 'تشخيص', 'is_correct' => true],
            //         ['text' => 'علاج', 'is_correct' => false],
            //         ['text' => 'فحص', 'is_correct' => false],
            //         ['text' => 'جراحة', 'is_correct' => false],
            //     ]),
            //     'difficulty' => 'medium',
            //     'points' => 2,
            //     'subject_id' => 5,
            //     'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
            //     'updated_at' => now(),
            // ],

            // Subject ID 6: English Language (1)
            // [
            //     'text' => 'What is the English word for "قلب"?',
            //     'answers' => json_encode([
            //         ['text' => 'Heart', 'is_correct' => true],
            //         ['text' => 'Liver', 'is_correct' => false],
            //         ['text' => 'Lung', 'is_correct' => false],
            //         ['text' => 'Brain', 'is_correct' => false],
            //     ]),
            //     'difficulty' => 'easy',
            //     'points' => 1,
            //     'subject_id' => 6,
            //     'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
            //     'updated_at' => now(),
            // ],
            // [
            //     'text' => 'Which of the following is the correct English translation for "مستشفى"?',
            //     'answers' => json_encode([
            //         ['text' => 'Hospital', 'is_correct' => true],
            //         ['text' => 'Clinic', 'is_correct' => false],
            //         ['text' => 'Pharmacy', 'is_correct' => false],
            //         ['text' => 'Laboratory', 'is_correct' => false],
            //     ]),
            //     'difficulty' => 'medium',
            //     'points' => 2,
            //     'subject_id' => 6,
            //     'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
            //     'updated_at' => now(),
            // ],
            // [
            //     'text' => 'What is the plural form of the English word "doctor"?',
            //     'answers' => json_encode([
            //         ['text' => 'Doctors', 'is_correct' => true],
            //         ['text' => 'Doctor\'s', 'is_correct' => false],
            //         ['text' => 'Doctores', 'is_correct' => false],
            //         ['text' => 'Doctories', 'is_correct' => false],
            //     ]),
            //     'difficulty' => 'hard',
            //     'points' => 3,
            //     'subject_id' => 6,
            //     'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
            //     'updated_at' => now(),
            // ],
            // [
            //     'text' => 'Which English word means "جراحة"?',
            //     'answers' => json_encode([
            //         ['text' => 'Surgery', 'is_correct' => true],
            //         ['text' => 'Medicine', 'is_correct' => false],
            //         ['text' => 'Treatment', 'is_correct' => false],
            //         ['text' => 'Drug', 'is_correct' => false],
            //     ]),
            //     'difficulty' => 'easy',
            //     'points' => 1,
            //     'subject_id' => 6,
            //     'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
            //     'updated_at' => now(),
            // ],
            // [
            //     'text' => 'What is the English term for "طوارئ"?',
            //     'answers' => json_encode([
            //         ['text' => 'Emergency', 'is_correct' => true],
            //         ['text' => 'Ambulance', 'is_correct' => false],
            //         ['text' => 'Case', 'is_correct' => false],
            //         ['text' => 'Urgent', 'is_correct' => false],
            //     ]),
            //     'difficulty' => 'medium',
            //     'points' => 2,
            //     'subject_id' => 6,
            //     'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
            //     'updated_at' => now(),
            // ],

            // Subject ID 7: English Language (2)
            // [
            //     'text' => 'What is the English word for "مريض"?',
            //     'answers' => json_encode([
            //         ['text' => 'Patient', 'is_correct' => true],
            //         ['text' => 'Doctor', 'is_correct' => false],
            //         ['text' => 'Nurse', 'is_correct' => false],
            //         ['text' => 'Surgeon', 'is_correct' => false],
            //     ]),
            //     'difficulty' => 'easy',
            //     'points' => 1,
            //     'subject_id' => 7,
            //     'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
            //     'updated_at' => now(),
            // ],
            // [
            //     'text' => 'Which of the following is the correct English translation for "صيدلية"?',
            //     'answers' => json_encode([
            //         ['text' => 'Pharmacy', 'is_correct' => true],
            //         ['text' => 'Hospital', 'is_correct' => false],
            //         ['text' => 'Clinic', 'is_correct' => false],
            //         ['text' => 'Laboratory', 'is_correct' => false],
            //     ]),
            //     'difficulty' => 'medium',
            //     'points' => 2,
            //     'subject_id' => 7,
            //     'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
            //     'updated_at' => now(),
            // ],
            // [
            //     'text' => 'What is the plural form of the English word "nurse"?',
            //     'answers' => json_encode([
            //         ['text' => 'Nurses', 'is_correct' => true],
            //         ['text' => 'Nurse\'s', 'is_correct' => false],
            //         ['text' => 'Nursies', 'is_correct' => false],
            //         ['text' => 'Nursen', 'is_correct' => false],
            //     ]),
            //     'difficulty' => 'hard',
            //     'points' => 3,
            //     'subject_id' => 7,
            //     'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
            //     'updated_at' => now(),
            // ],
            // [
            //     'text' => 'Which English word means "تشخيص"?',
            //     'answers' => json_encode([
            //         ['text' => 'Diagnosis', 'is_correct' => true],
            //         ['text' => 'Treatment', 'is_correct' => false],
            //         ['text' => 'Examination', 'is_correct' => false],
            //         ['text' => 'Surgery', 'is_correct' => false],
            //     ]),
            //     'difficulty' => 'easy',
            //     'points' => 1,
            //     'subject_id' => 7,
            //     'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
            //     'updated_at' => now(),
            // ],
            // [
            //     'text' => 'What is the English term for "إسعاف"?',
            //     'answers' => json_encode([
            //         ['text' => 'Ambulance', 'is_correct' => true],
            //         ['text' => 'Emergency', 'is_correct' => false],
            //         ['text' => 'Case', 'is_correct' => false],
            //         ['text' => 'Urgent', 'is_correct' => false],
            //     ]),
            //     'difficulty' => 'medium',
            //     'points' => 2,
            //     'subject_id' => 7,
            //     'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
            //     'updated_at' => now(),
            // ],

            // Subject ID 8: Computer Skills
            [
                'text' => 'What is the primary function of a CPU?',
                'answers' => json_encode([
                    ['text' => 'Process data', 'is_correct' => true],
                    ['text' => 'Store data', 'is_correct' => false],
                    ['text' => 'Display data', 'is_correct' => false],
                    ['text' => 'Input data', 'is_correct' => false],
                ]),
                'difficulty' => 'easy',
                'points' => 1,
                'subject_id' => 8,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'Which of the following is an example of an operating system?',
                'answers' => json_encode([
                    ['text' => 'Windows', 'is_correct' => true],
                    ['text' => 'Microsoft Word', 'is_correct' => false],
                    ['text' => 'Adobe Photoshop', 'is_correct' => false],
                    ['text' => 'Google Chrome', 'is_correct' => false],
                ]),
                'difficulty' => 'medium',
                'points' => 2,
                'subject_id' => 8,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'What does RAM stand for?',
                'answers' => json_encode([
                    ['text' => 'Random Access Memory', 'is_correct' => true],
                    ['text' => 'Read Access Memory', 'is_correct' => false],
                    ['text' => 'Random Available Memory', 'is_correct' => false],
                    ['text' => 'Read Available Memory', 'is_correct' => false],
                ]),
                'difficulty' => 'hard',
                'points' => 3,
                'subject_id' => 8,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'Which of the following is a programming language?',
                'answers' => json_encode([
                    ['text' => 'Python', 'is_correct' => true],
                    ['text' => 'Microsoft Excel', 'is_correct' => false],
                    ['text' => 'Adobe Illustrator', 'is_correct' => false],
                    ['text' => 'Google Drive', 'is_correct' => false],
                ]),
                'difficulty' => 'easy',
                'points' => 1,
                'subject_id' => 8,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'What is the primary function of a firewall?',
                'answers' => json_encode([
                    ['text' => 'Block unauthorized access', 'is_correct' => true],
                    ['text' => 'Store data', 'is_correct' => false],
                    ['text' => 'Process data', 'is_correct' => false],
                    ['text' => 'Display data', 'is_correct' => false],
                ]),
                'difficulty' => 'medium',
                'points' => 2,
                'subject_id' => 8,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],

            // Subject ID 9: Communication Skills
            [
                'text' => 'What is the primary goal of effective communication?',
                'answers' => json_encode([
                    ['text' => 'Understanding', 'is_correct' => true],
                    ['text' => 'Persuasion', 'is_correct' => false],
                    ['text' => 'Entertainment', 'is_correct' => false],
                    ['text' => 'Information', 'is_correct' => false],
                ]),
                'difficulty' => 'easy',
                'points' => 1,
                'subject_id' => 9,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'Which of the following is a barrier to effective communication?',
                'answers' => json_encode([
                    ['text' => 'Noise', 'is_correct' => true],
                    ['text' => 'Clarity', 'is_correct' => false],
                    ['text' => 'Feedback', 'is_correct' => false],
                    ['text' => 'Understanding', 'is_correct' => false],
                ]),
                'difficulty' => 'medium',
                'points' => 2,
                'subject_id' => 9,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'What is the most important aspect of non-verbal communication?',
                'answers' => json_encode([
                    ['text' => 'Body language', 'is_correct' => true],
                    ['text' => 'Tone of voice', 'is_correct' => false],
                    ['text' => 'Facial expressions', 'is_correct' => false],
                    ['text' => 'Eye contact', 'is_correct' => false],
                ]),
                'difficulty' => 'hard',
                'points' => 3,
                'subject_id' => 9,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'Which of the following is a type of verbal communication?',
                'answers' => json_encode([
                    ['text' => 'Speaking', 'is_correct' => true],
                    ['text' => 'Writing', 'is_correct' => false],
                    ['text' => 'Gestures', 'is_correct' => false],
                    ['text' => 'Facial expressions', 'is_correct' => false],
                ]),
                'difficulty' => 'easy',
                'points' => 1,
                'subject_id' => 9,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'What is the primary purpose of feedback in communication?',
                'answers' => json_encode([
                    ['text' => 'To ensure understanding', 'is_correct' => true],
                    ['text' => 'To entertain', 'is_correct' => false],
                    ['text' => 'To persuade', 'is_correct' => false],
                    ['text' => 'To inform', 'is_correct' => false],
                ]),
                'difficulty' => 'medium',
                'points' => 2,
                'subject_id' => 9,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],

            // Subject ID 10: Infection, Inflammation, and Tumors
            [
                'text' => 'What is the primary cause of bacterial infections?',
                'answers' => json_encode([
                    ['text' => 'Bacteria', 'is_correct' => true],
                    ['text' => 'Viruses', 'is_correct' => false],
                    ['text' => 'Fungi', 'is_correct' => false],
                    ['text' => 'Parasites', 'is_correct' => false],
                ]),
                'difficulty' => 'easy',
                'points' => 1,
                'subject_id' => 10,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'Which of the following is a sign of inflammation?',
                'answers' => json_encode([
                    ['text' => 'Redness', 'is_correct' => true],
                    ['text' => 'Pallor', 'is_correct' => false],
                    ['text' => 'Cyanosis', 'is_correct' => false],
                    ['text' => 'Jaundice', 'is_correct' => false],
                ]),
                'difficulty' => 'medium',
                'points' => 2,
                'subject_id' => 10,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'What is the most common cause of cancer?',
                'answers' => json_encode([
                    ['text' => 'Genetic mutations', 'is_correct' => true],
                    ['text' => 'Bacterial infections', 'is_correct' => false],
                    ['text' => 'Viral infections', 'is_correct' => false],
                    ['text' => 'Fungal infections', 'is_correct' => false],
                ]),
                'difficulty' => 'hard',
                'points' => 3,
                'subject_id' => 10,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'Which of the following is a type of tumor?',
                'answers' => json_encode([
                    ['text' => 'Benign', 'is_correct' => true],
                    ['text' => 'Infectious', 'is_correct' => false],
                    ['text' => 'Inflammatory', 'is_correct' => false],
                    ['text' => 'Autoimmune', 'is_correct' => false],
                ]),
                'difficulty' => 'easy',
                'points' => 1,
                'subject_id' => 10,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'What is the primary treatment for bacterial infections?',
                'answers' => json_encode([
                    ['text' => 'Antibiotics', 'is_correct' => true],
                    ['text' => 'Antivirals', 'is_correct' => false],
                    ['text' => 'Antifungals', 'is_correct' => false],
                    ['text' => 'Antiparasitics', 'is_correct' => false],
                ]),
                'difficulty' => 'medium',
                'points' => 2,
                'subject_id' => 10,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],

            // Subject ID 11: Blood Disorders, Immunity, and the Lymphatic System
            [
                'text' => 'What is the primary function of red blood cells?',
                'answers' => json_encode([
                    ['text' => 'Transport oxygen', 'is_correct' => true],
                    ['text' => 'Fight infections', 'is_correct' => false],
                    ['text' => 'Clot blood', 'is_correct' => false],
                    ['text' => 'Produce antibodies', 'is_correct' => false],
                ]),
                'difficulty' => 'easy',
                'points' => 1,
                'subject_id' => 11,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'Which of the following is a blood disorder?',
                'answers' => json_encode([
                    ['text' => 'Anemia', 'is_correct' => true],
                    ['text' => 'Arthritis', 'is_correct' => false],
                    ['text' => 'Asthma', 'is_correct' => false],
                    ['text' => 'Diabetes', 'is_correct' => false],
                ]),
                'difficulty' => 'medium',
                'points' => 2,
                'subject_id' => 11,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'What is the primary function of the lymphatic system?',
                'answers' => json_encode([
                    ['text' => 'Immune response', 'is_correct' => true],
                    ['text' => 'Blood circulation', 'is_correct' => false],
                    ['text' => 'Oxygen transport', 'is_correct' => false],
                    ['text' => 'Nutrient absorption', 'is_correct' => false],
                ]),
                'difficulty' => 'hard',
                'points' => 3,
                'subject_id' => 11,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'Which of the following is a type of immunity?',
                'answers' => json_encode([
                    ['text' => 'Adaptive immunity', 'is_correct' => true],
                    ['text' => 'Innate immunity', 'is_correct' => false],
                    ['text' => 'Passive immunity', 'is_correct' => false],
                    ['text' => 'Active immunity', 'is_correct' => false],
                ]),
                'difficulty' => 'easy',
                'points' => 1,
                'subject_id' => 11,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'What is the primary cause of hemophilia?',
                'answers' => json_encode([
                    ['text' => 'Genetic mutation', 'is_correct' => true],
                    ['text' => 'Bacterial infection', 'is_correct' => false],
                    ['text' => 'Viral infection', 'is_correct' => false],
                    ['text' => 'Fungal infection', 'is_correct' => false],
                ]),
                'difficulty' => 'medium',
                'points' => 2,
                'subject_id' => 11,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],

            // Subject ID 12: Circulatory and Respiratory Systems (Specialization)
            [
                'text' => 'What is the primary function of the circulatory system?',
                'answers' => json_encode([
                    ['text' => 'Transport blood', 'is_correct' => true],
                    ['text' => 'Filter toxins', 'is_correct' => false],
                    ['text' => 'Produce hormones', 'is_correct' => false],
                    ['text' => 'Digest food', 'is_correct' => false],
                ]),
                'difficulty' => 'easy',
                'points' => 1,
                'subject_id' => 12,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'Which of the following is a component of the respiratory system?',
                'answers' => json_encode([
                    ['text' => 'Lungs', 'is_correct' => true],
                    ['text' => 'Heart', 'is_correct' => false],
                    ['text' => 'Liver', 'is_correct' => false],
                    ['text' => 'Kidneys', 'is_correct' => false],
                ]),
                'difficulty' => 'medium',
                'points' => 2,
                'subject_id' => 12,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'What is the primary function of the alveoli?',
                'answers' => json_encode([
                    ['text' => 'Gas exchange', 'is_correct' => true],
                    ['text' => 'Blood filtration', 'is_correct' => false],
                    ['text' => 'Hormone production', 'is_correct' => false],
                    ['text' => 'Nutrient absorption', 'is_correct' => false],
                ]),
                'difficulty' => 'hard',
                'points' => 3,
                'subject_id' => 12,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'Which of the following is a symptom of asthma?',
                'answers' => json_encode([
                    ['text' => 'Wheezing', 'is_correct' => true],
                    ['text' => 'Chest pain', 'is_correct' => false],
                    ['text' => 'Headache', 'is_correct' => false],
                    ['text' => 'Abdominal pain', 'is_correct' => false],
                ]),
                'difficulty' => 'easy',
                'points' => 1,
                'subject_id' => 12,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'What is the primary cause of chronic obstructive pulmonary disease (COPD)?',
                'answers' => json_encode([
                    ['text' => 'Smoking', 'is_correct' => true],
                    ['text' => 'Air pollution', 'is_correct' => false],
                    ['text' => 'Genetic factors', 'is_correct' => false],
                    ['text' => 'Viral infections', 'is_correct' => false],
                ]),
                'difficulty' => 'medium',
                'points' => 2,
                'subject_id' => 12,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],

            // Subject ID 13: Community Medicine and Field Research Project
            [
                'text' => 'What is the primary goal of community medicine?',
                'answers' => json_encode([
                    ['text' => 'Improve public health', 'is_correct' => true],
                    ['text' => 'Treat individual patients', 'is_correct' => false],
                    ['text' => 'Conduct laboratory research', 'is_correct' => false],
                    ['text' => 'Develop new drugs', 'is_correct' => false],
                ]),
                'difficulty' => 'easy',
                'points' => 1,
                'subject_id' => 13,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'Which of the following is a method of data collection in field research?',
                'answers' => json_encode([
                    ['text' => 'Surveys', 'is_correct' => true],
                    ['text' => 'Laboratory experiments', 'is_correct' => false],
                    ['text' => 'Clinical trials', 'is_correct' => false],
                    ['text' => 'Case studies', 'is_correct' => false],
                ]),
                'difficulty' => 'medium',
                'points' => 2,
                'subject_id' => 13,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'What is the primary focus of epidemiology?',
                'answers' => json_encode([
                    ['text' => 'Disease patterns', 'is_correct' => true],
                    ['text' => 'Drug development', 'is_correct' => false],
                    ['text' => 'Patient care', 'is_correct' => false],
                    ['text' => 'Laboratory research', 'is_correct' => false],
                ]),
                'difficulty' => 'hard',
                'points' => 3,
                'subject_id' => 13,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'Which of the following is a key component of a field research project?',
                'answers' => json_encode([
                    ['text' => 'Data analysis', 'is_correct' => true],
                    ['text' => 'Patient interviews', 'is_correct' => false],
                    ['text' => 'Laboratory tests', 'is_correct' => false],
                    ['text' => 'Drug trials', 'is_correct' => false],
                ]),
                'difficulty' => 'easy',
                'points' => 1,
                'subject_id' => 13,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'What is the primary purpose of a control group in a research study?',
                'answers' => json_encode([
                    ['text' => 'Compare results', 'is_correct' => true],
                    ['text' => 'Receive treatment', 'is_correct' => false],
                    ['text' => 'Collect data', 'is_correct' => false],
                    ['text' => 'Analyze data', 'is_correct' => false],
                ]),
                'difficulty' => 'medium',
                'points' => 2,
                'subject_id' => 13,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],

            // Subject ID 14: Islamic Culture (1)
            // [
            //     'text' => 'What is the primary source of Islamic law?',
            //     'answers' => json_encode([
            //         ['text' => 'Quran', 'is_correct' => true],
            //         ['text' => 'Hadith', 'is_correct' => false],
            //         ['text' => 'Ijma', 'is_correct' => false],
            //         ['text' => 'Qiyas', 'is_correct' => false],
            //     ]),
            //     'difficulty' => 'easy',
            //     'points' => 1,
            //     'subject_id' => 14,
            //     'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
            //     'updated_at' => now(),
            // ],
            // [
            //     'text' => 'Which of the following is a pillar of Islam?',
            //     'answers' => json_encode([
            //         ['text' => 'Prayer', 'is_correct' => true],
            //         ['text' => 'Fasting', 'is_correct' => false],
            //         ['text' => 'Charity', 'is_correct' => false],
            //         ['text' => 'Pilgrimage', 'is_correct' => false],
            //     ]),
            //     'difficulty' => 'medium',
            //     'points' => 2,
            //     'subject_id' => 14,
            //     'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
            //     'updated_at' => now(),
            // ],
            // [
            //     'text' => 'What is the significance of the Hijra in Islamic history?',
            //     'answers' => json_encode([
            //         ['text' => 'Migration of Prophet Muhammad', 'is_correct' => true],
            //         ['text' => 'Birth of Prophet Muhammad', 'is_correct' => false],
            //         ['text' => 'First revelation', 'is_correct' => false],
            //         ['text' => 'Conquest of Mecca', 'is_correct' => false],
            //     ]),
            //     'difficulty' => 'hard',
            //     'points' => 3,
            //     'subject_id' => 14,
            //     'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
            //     'updated_at' => now(),
            // ],
            // [
            //     'text' => 'Which of the following is a key concept in Islamic ethics?',
            //     'answers' => json_encode([
            //         ['text' => 'Justice', 'is_correct' => true],
            //         ['text' => 'Wealth', 'is_correct' => false],
            //         ['text' => 'Power', 'is_correct' => false],
            //         ['text' => 'Fame', 'is_correct' => false],
            //     ]),
            //     'difficulty' => 'easy',
            //     'points' => 1,
            //     'subject_id' => 14,
            //     'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
            //     'updated_at' => now(),
            // ],
            // [
            //     'text' => 'What is the primary purpose of Zakat in Islam?',
            //     'answers' => json_encode([
            //         ['text' => 'Support the needy', 'is_correct' => true],
            //         ['text' => 'Fund mosques', 'is_correct' => false],
            //         ['text' => 'Support the government', 'is_correct' => false],
            //         ['text' => 'Fund wars', 'is_correct' => false],
            //     ]),
            //     'difficulty' => 'medium',
            //     'points' => 2,
            //     'subject_id' => 14,
            //     'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
            //     'updated_at' => now(),
            // ],

            // Subject ID 15: Islamic Culture (2)
            // [
            //     'text' => 'What is the significance of the Kaaba in Islam?',
            //     'answers' => json_encode([
            //         ['text' => 'House of God', 'is_correct' => true],
            //         ['text' => 'Prophet\'s birthplace', 'is_correct' => false],
            //         ['text' => 'First mosque', 'is_correct' => false],
            //         ['text' => 'Place of revelation', 'is_correct' => false],
            //     ]),
            //     'difficulty' => 'easy',
            //     'points' => 1,
            //     'subject_id' => 15,
            //     'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
            //     'updated_at' => now(),
            // ],
            // [
            //     'text' => 'Which of the following is a key principle of Islamic finance?',
            //     'answers' => json_encode([
            //         ['text' => 'Prohibition of interest', 'is_correct' => true],
            //         ['text' => 'High-risk investments', 'is_correct' => false],
            //         ['text' => 'Speculation', 'is_correct' => false],
            //         ['text' => 'Debt accumulation', 'is_correct' => false],
            //     ]),
            //     'difficulty' => 'medium',
            //     'points' => 2,
            //     'subject_id' => 15,
            //     'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
            //     'updated_at' => now(),
            // ],
            // [
            //     'text' => 'What is the primary purpose of Hajj in Islam?',
            //     'answers' => json_encode([
            //         ['text' => 'Spiritual purification', 'is_correct' => true],
            //         ['text' => 'Social gathering', 'is_correct' => false],
            //         ['text' => 'Economic benefit', 'is_correct' => false],
            //         ['text' => 'Political influence', 'is_correct' => false],
            //     ]),
            //     'difficulty' => 'hard',
            //     'points' => 3,
            //     'subject_id' => 15,
            //     'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
            //     'updated_at' => now(),
            // ],
            // [
            //     'text' => 'Which of the following is a key concept in Islamic art?',
            //     'answers' => json_encode([
            //         ['text' => 'Geometric patterns', 'is_correct' => true],
            //         ['text' => 'Human figures', 'is_correct' => false],
            //         ['text' => 'Animal figures', 'is_correct' => false],
            //         ['text' => 'Landscapes', 'is_correct' => false],
            //     ]),
            //     'difficulty' => 'easy',
            //     'points' => 1,
            //     'subject_id' => 15,
            //     'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
            //     'updated_at' => now(),
            // ],
            // [
            //     'text' => 'What is the primary purpose of fasting in Ramadan?',
            //     'answers' => json_encode([
            //         ['text' => 'Spiritual discipline', 'is_correct' => true],
            //         ['text' => 'Physical health', 'is_correct' => false],
            //         ['text' => 'Social bonding', 'is_correct' => false],
            //         ['text' => 'Economic benefit', 'is_correct' => false],
            //     ]),
            //     'difficulty' => 'medium',
            //     'points' => 2,
            //     'subject_id' => 15,
            //     'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
            //     'updated_at' => now(),
            // ],

            // Subject ID 16: Digestive and Motor Systems
            [
                'text' => 'What is the primary function of the stomach?',
                'answers' => json_encode([
                    ['text' => 'Digest food', 'is_correct' => true],
                    ['text' => 'Absorb nutrients', 'is_correct' => false],
                    ['text' => 'Produce bile', 'is_correct' => false],
                    ['text' => 'Filter toxins', 'is_correct' => false],
                ]),
                'difficulty' => 'easy',
                'points' => 1,
                'subject_id' => 16,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'Which of the following is a component of the digestive system?',
                'answers' => json_encode([
                    ['text' => 'Small intestine', 'is_correct' => true],
                    ['text' => 'Heart', 'is_correct' => false],
                    ['text' => 'Lungs', 'is_correct' => false],
                    ['text' => 'Kidneys', 'is_correct' => false],
                ]),
                'difficulty' => 'medium',
                'points' => 2,
                'subject_id' => 16,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'What is the primary function of the liver?',
                'answers' => json_encode([
                    ['text' => 'Detoxify chemicals', 'is_correct' => true],
                    ['text' => 'Digest food', 'is_correct' => false],
                    ['text' => 'Absorb nutrients', 'is_correct' => false],
                    ['text' => 'Produce insulin', 'is_correct' => false],
                ]),
                'difficulty' => 'hard',
                'points' => 3,
                'subject_id' => 16,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'Which of the following is a symptom of gastritis?',
                'answers' => json_encode([
                    ['text' => 'Abdominal pain', 'is_correct' => true],
                    ['text' => 'Chest pain', 'is_correct' => false],
                    ['text' => 'Headache', 'is_correct' => false],
                    ['text' => 'Joint pain', 'is_correct' => false],
                ]),
                'difficulty' => 'easy',
                'points' => 1,
                'subject_id' => 16,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'What is the primary cause of peptic ulcers?',
                'answers' => json_encode([
                    ['text' => 'H. pylori infection', 'is_correct' => true],
                    ['text' => 'High-fat diet', 'is_correct' => false],
                    ['text' => 'Stress', 'is_correct' => false],
                    ['text' => 'Alcohol consumption', 'is_correct' => false],
                ]),
                'difficulty' => 'medium',
                'points' => 2,
                'subject_id' => 16,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],

            // Subject ID 17: Nervous System
            [
                'text' => 'What is the primary function of the nervous system?',
                'answers' => json_encode([
                    ['text' => 'Transmit signals', 'is_correct' => true],
                    ['text' => 'Pump blood', 'is_correct' => false],
                    ['text' => 'Filter toxins', 'is_correct' => false],
                    ['text' => 'Digest food', 'is_correct' => false],
                ]),
                'difficulty' => 'easy',
                'points' => 1,
                'subject_id' => 17,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'Which of the following is a component of the nervous system?',
                'answers' => json_encode([
                    ['text' => 'Brain', 'is_correct' => true],
                    ['text' => 'Heart', 'is_correct' => false],
                    ['text' => 'Lungs', 'is_correct' => false],
                    ['text' => 'Kidneys', 'is_correct' => false],
                ]),
                'difficulty' => 'medium',
                'points' => 2,
                'subject_id' => 17,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'What is the primary function of neurons?',
                'answers' => json_encode([
                    ['text' => 'Transmit electrical signals', 'is_correct' => true],
                    ['text' => 'Produce hormones', 'is_correct' => false],
                    ['text' => 'Filter toxins', 'is_correct' => false],
                    ['text' => 'Digest food', 'is_correct' => false],
                ]),
                'difficulty' => 'hard',
                'points' => 3,
                'subject_id' => 17,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'Which of the following is a symptom of a stroke?',
                'answers' => json_encode([
                    ['text' => 'Sudden numbness', 'is_correct' => true],
                    ['text' => 'Chest pain', 'is_correct' => false],
                    ['text' => 'Headache', 'is_correct' => false],
                    ['text' => 'Abdominal pain', 'is_correct' => false],
                ]),
                'difficulty' => 'easy',
                'points' => 1,
                'subject_id' => 17,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'What is the primary cause of Parkinson\'s disease?',
                'answers' => json_encode([
                    ['text' => 'Loss of dopamine-producing neurons', 'is_correct' => true],
                    ['text' => 'High blood pressure', 'is_correct' => false],
                    ['text' => 'Genetic mutation', 'is_correct' => false],
                    ['text' => 'Viral infection', 'is_correct' => false],
                ]),
                'difficulty' => 'medium',
                'points' => 2,
                'subject_id' => 17,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],

            // Subject ID 18: Urinary System and Endocrinology
            [
                'text' => 'What is the primary function of the kidneys?',
                'answers' => json_encode([
                    ['text' => 'Filter blood', 'is_correct' => true],
                    ['text' => 'Produce hormones', 'is_correct' => false],
                    ['text' => 'Digest food', 'is_correct' => false],
                    ['text' => 'Pump blood', 'is_correct' => false],
                ]),
                'difficulty' => 'easy',
                'points' => 1,
                'subject_id' => 18,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'Which of the following is a component of the urinary system?',
                'answers' => json_encode([
                    ['text' => 'Bladder', 'is_correct' => true],
                    ['text' => 'Heart', 'is_correct' => false],
                    ['text' => 'Lungs', 'is_correct' => false],
                    ['text' => 'Liver', 'is_correct' => false],
                ]),
                'difficulty' => 'medium',
                'points' => 2,
                'subject_id' => 18,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'What is the primary function of the endocrine system?',
                'answers' => json_encode([
                    ['text' => 'Produce hormones', 'is_correct' => true],
                    ['text' => 'Filter blood', 'is_correct' => false],
                    ['text' => 'Digest food', 'is_correct' => false],
                    ['text' => 'Pump blood', 'is_correct' => false],
                ]),
                'difficulty' => 'hard',
                'points' => 3,
                'subject_id' => 18,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'Which of the following is a symptom of diabetes?',
                'answers' => json_encode([
                    ['text' => 'Frequent urination', 'is_correct' => true],
                    ['text' => 'Chest pain', 'is_correct' => false],
                    ['text' => 'Headache', 'is_correct' => false],
                    ['text' => 'Abdominal pain', 'is_correct' => false],
                ]),
                'difficulty' => 'easy',
                'points' => 1,
                'subject_id' => 18,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'What is the primary cause of hyperthyroidism?',
                'answers' => json_encode([
                    ['text' => 'Overactive thyroid gland', 'is_correct' => true],
                    ['text' => 'Underactive thyroid gland', 'is_correct' => false],
                    ['text' => 'Genetic mutation', 'is_correct' => false],
                    ['text' => 'Viral infection', 'is_correct' => false],
                ]),
                'difficulty' => 'medium',
                'points' => 2,
                'subject_id' => 18,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],

            // Subject ID 19: Community Medicine and Field Research Project (2)
            [
                'text' => 'What is the primary goal of epidemiology?',
                'answers' => json_encode([
                    ['text' => 'Study disease patterns', 'is_correct' => true],
                    ['text' => 'Treat individual patients', 'is_correct' => false],
                    ['text' => 'Develop new drugs', 'is_correct' => false],
                    ['text' => 'Conduct laboratory research', 'is_correct' => false],
                ]),
                'difficulty' => 'easy',
                'points' => 1,
                'subject_id' => 19,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'Which of the following is a method of data analysis in field research?',
                'answers' => json_encode([
                    ['text' => 'Statistical analysis', 'is_correct' => true],
                    ['text' => 'Patient interviews', 'is_correct' => false],
                    ['text' => 'Laboratory tests', 'is_correct' => false],
                    ['text' => 'Drug trials', 'is_correct' => false],
                ]),
                'difficulty' => 'medium',
                'points' => 2,
                'subject_id' => 19,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'What is the primary focus of public health?',
                'answers' => json_encode([
                    ['text' => 'Prevent disease', 'is_correct' => true],
                    ['text' => 'Treat disease', 'is_correct' => false],
                    ['text' => 'Develop new drugs', 'is_correct' => false],
                    ['text' => 'Conduct laboratory research', 'is_correct' => false],
                ]),
                'difficulty' => 'hard',
                'points' => 3,
                'subject_id' => 19,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'Which of the following is a key component of a research proposal?',
                'answers' => json_encode([
                    ['text' => 'Research question', 'is_correct' => true],
                    ['text' => 'Patient interviews', 'is_correct' => false],
                    ['text' => 'Laboratory tests', 'is_correct' => false],
                    ['text' => 'Drug trials', 'is_correct' => false],
                ]),
                'difficulty' => 'easy',
                'points' => 1,
                'subject_id' => 19,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
            [
                'text' => 'What is the primary purpose of a literature review in research?',
                'answers' => json_encode([
                    ['text' => 'Summarize existing knowledge', 'is_correct' => true],
                    ['text' => 'Collect data', 'is_correct' => false],
                    ['text' => 'Analyze data', 'is_correct' => false],
                    ['text' => 'Develop hypotheses', 'is_correct' => false],
                ]),
                'difficulty' => 'medium',
                'points' => 2,
                'subject_id' => 19,
                'created_at' => now()->subDays(rand(1, 30))->subHours(rand(1, 24))->subMinutes(rand(1, 60)),
                'updated_at' => now(),
            ],
        ]);
    }
}
